### ISSUE TITLE
Feature: Add support for input plugin tags 

### ISSUE THREAD

**Issue by adilnaimi** [mrlesmithjr/ansible-telegraf#1]
This is not really an issue, it just would be nice to be able to add support for the [input plugins tags](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tags).

Telegraf saying that the order matters, the [inputs.cpu.tags] table must be at the end of the plugin definition.
Example:
```toml
[[inputs.cpu]]
  percpu = false
  totalcpu = true
  [inputs.cpu.tags]
    tag1 = "foo"
    tag2 = "bar"
```
